# Default values for wikijs

image: requarks/wiki:2
storage:
  class: scw-bssd
  size: 2Gi
ingress:
  hosts: [ wiki.tcbv.be, wiki.tcorp.me ]
  gateways: [ gw-wiki-tcbv-be.istio-system, gw-wiki-tcorp-me.istio-system ]
