# Default values for wikijs

image: requarks/wiki:canary-2.5.147@sha256:fd2df27db6a7efbf667e4f96e60af20ecb12f85d5ab1aecbca8d9fb51b370dce
storage:
  class: scw-bssd
  size: 2Gi
ingress:
  type: istio
  hosts:
  - wiki.tcbv.be
  - wiki.tcorp.me
  gateways:
  - gw-wiki-tcbv-be.istio-system
  - gw-wiki-tcorp-me.istio-system
