# Default values for wikijs

image: requarks/wiki:2.5@sha256:7d608a34f94faa37b542c33c0f04e22495d0c13569df7d54ea746ddd9459f059
storage:
  class: scw-bssd
  size: 2Gi
ingress:
  type: istio
  hosts:
  - wiki.tcbv.be
  - wiki.tcorp.me
  gateways:
  - gw-wiki-tcbv-be.istio-system
  - gw-wiki-tcorp-me.istio-system
