# Default values for wikijs

image: requarks/wiki:canary-2.4.105@sha256:75e48bfa5267be381831031a9f87287a839a81b6f3bef5339a91aa291934e35c
storage:
  class: scw-bssd
  size: 2Gi
ingress:
  type: istio
  hosts:
  - wiki.tcbv.be
  - wiki.tcorp.me
  gateways:
  - gw-wiki-tcbv-be.istio-system
  - gw-wiki-tcorp-me.istio-system
