apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikijs
  labels:
    app: wikijs
    track: stable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikijs
  strategy:
    type: Recreate
  template: # Pod specification
    metadata:
      labels:
        app: wikijs
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default # Security against syscalls
    spec:
      volumes:
      - name: vol
        persistentVolumeClaim:
          claimName: wikijs-pvc
      securityContext: # Security so the process runs as a normal user
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 2000
      containers:
      - name: wikijs
        image: {{ .Values.image }}
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
        env:
          - name: DB_TYPE
            value: sqlite
          - name: DB_FILEPATH
            value: /wiki/data/db
          - name: USE_HTTPS
            value: "0"
          - name: NO_PROXY
            value: localhost
        resources:
          requests:
            cpu: 100m
            memory: 150Mi
          limits:
            cpu: 2000m
            memory: 1Gi
        ports:
        - containerPort: 3000
        securityContext: # Security so the process runs as a normal user
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true # Ensure the process does not change anything on the root filesystem except the volumemount
          capabilities: # Drop any capabilities except for listening on the network
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        volumeMounts: # Mount the database volume (sqlite)
        - name: vol
          mountPath: "/wiki/data"
---
# The database volume (will contain sqlite etc)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wikijs-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: {{ .Values.storage.class }}
