apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: wikijs
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: wikijs
          servicePort: 80
