apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: wikijs
spec:
  hosts: {{ .Values.ingress.hosts }}
  gateways: {{ .Values.ingress.gateways }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: wikijs.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 80
