apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: wikijs
spec:
  hosts: {{ .Values.hosts }}
  gateways:
  - gw-wiki-tcbv-be.istio-system
  - gw-wiki-tcorp-me.istio-system
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: wikijs.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 80
