{{ if eq .Values.ingress.type "istio" }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: wikijs
spec:
  hosts: 
  {{- range .Values.ingress.hosts }}
  - {{ . | quote }}
  {{- end }}
  gateways: 
  {{- range .Values.ingress.gateways }}
  - {{ . | quote }}
  {{- end }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: wikijs
        port:
          number: 80
{{- end }}
